// -----------------------------------------------------------------------------------------------
// Build fix for error CS0656 "Missing compiler required member
// 'System.Runtime.CompilerServices.NullableAttribute..ctor'".
//
// Cause (verified in the supplied interop): BepInEx\interop\UnityEngine.CoreModule.dll, generated by
// Il2CppInterop, contains PUBLIC, EMPTY copies of
//     public sealed class System.Runtime.CompilerServices.NullableAttribute : Attribute { }
//     public sealed class System.Runtime.CompilerServices.NullableContextAttribute : Attribute { }
// with none of the constructors the C# compiler needs. When the compiler has to emit nullability
// metadata (for example for a lambda), it finds these referenced types instead of generating its own,
// and fails.
//
// The compiler always prefers a type declared in the project being compiled over one from a reference,
// so declaring correct internal versions here makes it use these. They are only compile-time metadata
// and have no effect at runtime.
// -----------------------------------------------------------------------------------------------

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Event | AttributeTargets.Field |
                    AttributeTargets.GenericParameter | AttributeTargets.Parameter | AttributeTargets.Property |
                    AttributeTargets.ReturnValue, AllowMultiple = false, Inherited = false)]
    internal sealed class NullableAttribute : Attribute
    {
        public readonly byte[] NullableFlags;
        public NullableAttribute(byte flag) { NullableFlags = new[] { flag }; }
        public NullableAttribute(byte[] flags) { NullableFlags = flags; }
    }

    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Delegate | AttributeTargets.Interface |
                    AttributeTargets.Method | AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
    internal sealed class NullableContextAttribute : Attribute
    {
        public readonly byte Flag;
        public NullableContextAttribute(byte flag) { Flag = flag; }
    }
}
